name: Build APK from AAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (free/paid)'
        required: true
        default: 'free'
        type: choice
        options:
          - 'free'
          - 'paid'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install dependencies and set up project
      run: yarn setup

    - name: Build unsigned release AAB
      run: yarn build android ${{ inputs.build_type }} dev

    - name: Download bundletool
      run: |
        wget https://github.com/google/bundletool/releases/download/1.18.1/bundletool-all-1.18.1.jar -O bundletool.jar

    - name: Build universal APK from AAB
      run: |
        java -jar bundletool.jar build-apks --bundle=platforms/android/app/build/outputs/bundle/release/app-release.aab --mode=universal --output=platforms/android/app/build/outputs/apk/release/app-release-unsigned.apks
        unzip platforms/android/app/build/outputs/apk/release/app-release-unsigned.apks -d platforms/android/app/build/outputs/apk/release/
        mv platforms/android/app/build/outputs/apk/release/universal.apk platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Upload unsigned APK
      uses: actions/upload-artifact@v4
      with:
        name: Acode-Unsigned-Release
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk